enableColors: true

nmHoistingLimits: workspaces

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.3.cjs

packageExtensions:
  "@privy-io/react-auth@*":
    peerDependencies:
      bs58: "*"
      lit: "*"
  "@reown/appkit@*":
    peerDependencies:
      "@types/react": "*"
      lit: "*"
  "react-hot-toast@*":
    peerDependencies:
      csstype: "*"
  "kubo-rpc-client@*":
    peerDependencies:
      undici: "*"
  "@solana/wallet-standard-wallet-adapter-react@*":
    peerDependencies:
      bs58: "*"
      "@solana/web3.js": "*"
  "@walletconnect/ethereum-provider@*":
    peerDependencies:
      "@types/react": "*"
      lit: "*"
  "bgipfs@*":
    peerDependencies:
      undici: "*"
  "ipfs-uploader@*":
    peerDependencies:
      undici: "*"
  "@wagmi/connectors@*":
    peerDependencies:
      "@types/react": "*"
      lit: "*"
  "burner-connector@*":
    peerDependencies:
      "@tanstack/react-query": "*"
      react: "*"
      react-dom: "*"
      lit: "*"
  "@stylistic/eslint-plugin@*":
    peerDependencies:
      typescript: "*"
  "eslint-plugin-n@*":
    peerDependencies:
      typescript: "*"
  "wagmi@*":
    peerDependencies:
      lit: "*"
